project:
  type: website
  output-dir: 'docs'
  

website:
  title: "Data visualization using Quarto and ggplot2"
  body-footer: <div style="text-align:center">The University of Utah</div>
  repo-url: https://github.com/UofUEpiBio/intro-r-ggplot2-quarto
  repo-actions: [edit, source]
  navbar:
    logo: gsrm_logo.png
    left:
      - href: index.qmd
        text: Home
      - href: 01-r.qmd
        text: R basics
      - href: 02-quarto.qmd
        text: Quarto
      - href: 03-ggplot2.qmd
        text: ggplot2
    right:
      - href: Git
        icon: github
        

format:
  html:
    theme: cosmo
    # css: styles.css
    toc: true

execute: 
  freeze: auto